Repository ssm-lab/capstone--source-code-optimizer, pull requests merged in 2025-04, with the labels that each got.

#581 [VNV PLAN] Updated Document with All Feedback and Revisions
  .github/workflows/pdf_builder.yaml
  docs/Makefile
  docs/VnVPlan/VnVPlan.pdf
  docs/VnVPlan/VnVPlan.tex
  docs/VnVReport/VnVReport.tex
  refs/References.bib
Labels: documentation, vnv-plan

#572 [Reflect Trace] Reflect and Trace Document
  docs/ReflectAndTrace/ReflectAndTrace.pdf
  docs/ReflectAndTrace/ReflectAndTrace.tex
  docs/projMngmnt/Final_Team_Contrib.pdf
  refs/References.bib
Labels: documentation

#583 [VNV REPORT] Updated Document with All Feedback and Revisions
  docs/Images/vscode-coverage.png
  docs/VnVReport/VnVReport.pdf
  docs/VnVReport/VnVReport.tex
Labels: documentation, vnv-report

#585 [DOCS] FINAL ADJUSTMENTS
  Final_Team_Contrib.pdf
  docs/Design/SoftDetailedDes/MIS.tex
  docs/HazardAnalysis/HazardAnalysis.tex
  docs/ProblemStatementAndGoals/ProblemStatement.tex
  docs/SRS/SRS.tex
  docs/UserGuide/Makefile
  docs/UserGuide/README.md
  docs/UserGuide/UserGuide.tex
  docs/VnVReport/VnVReport.tex
Labels: documentation

#580 [DOCS] [ALL] Final Documentation
  .github/workflows/pdf_builder.yaml
  Final_Team_Contrib.pdf
  README.md
  docs/Design/README.md
  docs/Design/SoftArchitecture/MG.pdf
  docs/Design/SoftArchitecture/MG.tex
  docs/Design/SoftArchitecture/README.md
  docs/Design/SoftDetailedDes/MIS.pdf
  docs/Design/SoftDetailedDes/MIS.tex
  docs/Design/SoftDetailedDes/README.md
  docs/DevelopmentPlan/README.md
  docs/HazardAnalysis/HazardAnalysis.tex
  docs/HazardAnalysis/README.md
  docs/Images/plugin_use_diagram.png
  docs/Images/sco_use_diagram.png
  docs/Images/vscode-coverage.png
  docs/Makefile
  docs/Presentations/README.md
  docs/ProblemStatementAndGoals/ProblemStatement.tex
  docs/ProblemStatementAndGoals/README.md
  docs/README.md
  docs/ReflectAndTrace/README.md
  docs/ReflectAndTrace/ReflectAndTrace.pdf
  docs/ReflectAndTrace/ReflectAndTrace.tex
  docs/SRS/README.md
  docs/SRS/SRS.pdf
  docs/SRS/SRS.tex
  docs/UserGuide/Makefile
  docs/UserGuide/README.md
  docs/UserGuide/UserGuide.tex
  docs/VnVPlan/README.md
  docs/VnVPlan/VnVPlan.pdf
  docs/VnVPlan/VnVPlan.tex
  docs/VnVReport/README.md
  docs/VnVReport/VnVReport.pdf
  docs/VnVReport/VnVReport.tex
  docs/projMngmnt/Final_Team_Contrib.pdf
  plugin/README.md
  refs/README.md
  refs/References.bib
  src/ecooptimizer/README.md
  tests/README.md
Labels: documentation
